const CHANGELOG = [
  {
    version: "v18.5.16",
    title: "Full Changelog History",
    date: "2026-06-02",
    type: "Dashboard / System",
    summary: "Expanded the changelog command so it shows full start-to-latest history instead of only a few recent entries.",
    changes: [
      "Added full historical changelog entries from v0.1 to the latest version.",
      "Improved changelog page data so the button menu has proper older versions to browse.",
      "Kept /changelog private and $changelog user-restricted.",
    ],
  },
  {
    version: "v18.5.15",
    title: "AI Ticket Dashboard Routing + Changelog Buttons",
    date: "2026-06-02",
    type: "AI Tickets / Commands",
    summary: "Made AI ticket category/channel routing editable from the dashboard and rebuilt the changelog command with buttons.",
    changes: [
      "AI ticket category IDs can be edited from the dashboard.",
      "Review channel and ping role can be edited from the dashboard.",
      "AI ticket routing saves to MongoDB per server.",
      "Changelog command now uses buttons: First, Previous, Next, Latest, Close.",
      "Slash changelog is private/ephemeral.",
      "Prefix changelog is restricted to the command runner and auto-cleans.",
    ],
  },
  {
    version: "v18.5.14",
    title: "Selector Redirect Emergency Fix",
    date: "2026-06-02",
    type: "Dashboard / Redirects",
    summary: "Fixed owner and customer server selector redirects and stopped AJAX from catching selector/login forms.",
    changes: [
      "Fixed dashboard/server.js export so the web server starts correctly.",
      "Owner server selector now redirects normally.",
      "Customer manage-server selector bypasses AJAX.",
      "Owner login form bypasses AJAX.",
      "Premium toggle form bypasses AJAX.",
      "Fixed repeated Invalid server selected toast spam.",
    ],
  },
  {
    version: "v18.5.13",
    title: "Dashboard Export Fix",
    date: "2026-06-02",
    type: "Dashboard / Hotfix",
    summary: "Fixed a broken dashboard export that stopped the web server from starting.",
    changes: [
      "Restored module.exports = startDashboard.",
      "Stopped exporting getScopedPath by mistake.",
      "Dashboard server can start again after deployment.",
    ],
  },
  {
    version: "v18.5.12",
    title: "Premium UI Spacing Polish",
    date: "2026-05-29",
    type: "Dashboard UI",
    summary: "Made premium toast/error/help UI less cramped and cleaner.",
    changes: [
      "Wider success and error cards.",
      "Cleaner help popup layout.",
      "Better spacing for bullets and messages.",
      "Improved mobile layout.",
      "Bigger premium loading orb.",
      "Smarter help text for invalid server/session/permission errors.",
    ],
  },
  {
    version: "v18.5.11",
    title: "Login + Selector Redirect Loader Fix",
    date: "2026-05-29",
    type: "Dashboard / Login",
    summary: "Fixed owner/customer login and server selector redirect flow.",
    changes: [
      "Owner login redirects to server selector correctly.",
      "Customer Discord login flow gets loader support.",
      "Customer server selector redirects to dashboard correctly.",
      "Redirect-style forms bypass AJAX but still show loader.",
    ],
  },
  {
    version: "v18.5.10",
    title: "Global Loader Everywhere",
    date: "2026-05-29",
    type: "Dashboard UI",
    summary: "Added the premium loading animation across owner and customer dashboard navigation.",
    changes: [
      "Same-site navigation links show loader.",
      "Owner pages show loader during navigation.",
      "Customer pages show loader during navigation.",
      "Normal non-AJAX form submits show loader.",
      "AJAX saves still use loader and toast.",
    ],
  },
  {
    version: "v18.5.9",
    title: "Server Selector AJAX Bypass Fix",
    date: "2026-05-29",
    type: "Dashboard / Hotfix",
    summary: "Stopped the server selector from being treated as a settings-save form.",
    changes: [
      "Server cards open using normal redirect.",
      "Premium toggle on selector works normally.",
      "Dashboard settings still use AJAX/no-redirect saves.",
    ],
  },
  {
    version: "v18.5.8",
    title: "Dashboard Export Hotfix",
    date: "2026-05-29",
    type: "Dashboard / Hotfix",
    summary: "Fixed a server export issue that prevented dashboard startup.",
    changes: [
      "Restored correct dashboard start function export.",
      "Kept premium loading/toast system.",
      "Restored web startup behavior.",
    ],
  },
  {
    version: "v18.5.7",
    title: "Premium Dashboard UX",
    date: "2026-05-29",
    type: "Dashboard UI",
    summary: "Added premium green/red toast cards, error help popup, and unsaved changes bar.",
    changes: [
      "Success popup uses green card style.",
      "Error popup uses red card style.",
      "Error popup includes ? help button.",
      "Help modal explains possible issue and fixes.",
      "Unsaved changes bar slides up from bottom.",
      "Added Reset, Factory Reset, and Save Changes buttons.",
      "Loading screen changed to animation only.",
    ],
  },
  {
    version: "v18.5.6",
    title: "Global Dashboard Toast UX",
    date: "2026-05-29",
    type: "Dashboard UI",
    summary: "Added global AJAX saves and bottom-right toast notifications.",
    changes: [
      "Owner dashboard forms use AJAX where possible.",
      "Customer dashboard forms use AJAX where possible.",
      "Success/error messages become toast popups.",
      "Toast location moved to bottom-right.",
      "Toast auto-closes with countdown and progress bar.",
    ],
  },
  {
    version: "v18.5.5",
    title: "Dashboard Loading + Toast System",
    date: "2026-05-29",
    type: "Dashboard UI",
    summary: "Initial dashboard no-redirect save experience.",
    changes: [
      "Added loading overlay.",
      "Added button loading state.",
      "AI Tickets save avoids full reload.",
      "Redirect messages convert to toast popups.",
    ],
  },
  {
    version: "v18.5.4",
    title: "AI Tickets UI + Score Max",
    date: "2026-05-26",
    type: "AI Tickets / Dashboard",
    summary: "Improved AI Tickets UI and added custom final score max.",
    changes: [
      "Added Final Score Out Of setting.",
      "AI Tickets main page became module selection.",
      "Staff Applications got a separate settings page.",
      "Other modules show not-ready placeholders.",
      "Added back button between AI ticket modules.",
    ],
  },
  {
    version: "v18.5.3",
    title: "Owner Dashboard AI Tickets Nav Fix",
    date: "2026-05-26",
    type: "Dashboard / Hotfix",
    summary: "Fixed AI Tickets owner dashboard navigation/sidebar issue.",
    changes: [
      "Removed broken sidebar AI Tickets link.",
      "Added AI Tickets properly in Server Management nav.",
      "Added safer dashboard error logging.",
    ],
  },
  {
    version: "v18.5.2",
    title: "Owner AI Tickets Panel Shortcut",
    date: "2026-05-26",
    type: "Dashboard",
    summary: "Added owner dashboard shortcut and module placeholders.",
    changes: [
      "Added AI Tickets card in owner Server Management.",
      "Added Staff Applications ready module.",
      "Added Ban Appeals, Warn Appeals, Partnerships, and Support AI placeholders.",
    ],
  },
  {
    version: "v18.5.1",
    title: "AI Ticket Manual Next Flow",
    date: "2026-05-26",
    type: "AI Tickets",
    summary: "Made staff application answers support multiple messages using $next.",
    changes: [
      "Users can answer in multiple messages.",
      "Bot only moves to next question when user types $next.",
      "Added $back, $finish, and $cancelapplication.",
      "Kept AI calls low with final review only.",
      "Added AI-copy suspicion scoring and score cap.",
    ],
  },
  {
    version: "v18.5.0",
    title: "AI Ticket Staff Application Core",
    date: "2026-05-26",
    type: "AI Tickets",
    summary: "Built the first AI TicketTool staff application system.",
    changes: [
      "Added TicketTool category detection.",
      "Added staff application interview flow.",
      "Added final AI/local review result.",
      "Added score, pass/review/reject logic.",
      "Added review channel report support.",
      "Added webhook report support.",
    ],
  },
  {
    version: "v18.4.0",
    title: "Help Command Role-Aware System",
    date: "2026-05-14",
    type: "Commands",
    summary: "Rebuilt the help system with role-aware pages and button navigation.",
    changes: [
      "Normal users see public commands.",
      "Staff and mod roles get extra command sections.",
      "Help menu uses previous/home/next buttons.",
      "Prefix help and slash help both supported.",
      "Help output is private/user-restricted where possible.",
    ],
  },
  {
    version: "v18.3.0",
    title: "Sports Lock Fix + Split DB Stability",
    date: "2026-05-18",
    type: "Sports / Database",
    summary: "Fixed sports channel lock issues and improved split database checks.",
    changes: [
      "Football and cricket locked channel settings load correctly.",
      "Sports settings persist better after restart.",
      "Added split DB status tools.",
      "Improved DB connection status output.",
    ],
  },
  {
    version: "v18.2.0",
    title: "Split Database Migration Tools",
    date: "2026-05-18",
    type: "Database",
    summary: "Added scripts and routing for multiple MongoDB URLs.",
    changes: [
      "Added db:status script.",
      "Added db:migrate:dry script.",
      "Added db:migrate script.",
      "Added db:migrate:overwrite script.",
      "Separated owner, server, customer, customer server, and logs connections.",
    ],
  },
  {
    version: "v18.1.0",
    title: "Owner/Customer Dashboard Fixes",
    date: "2026-05-18",
    type: "Dashboard",
    summary: "Fixed several owner/customer dashboard routes and locked feature behavior.",
    changes: [
      "Fixed customer manage route issues.",
      "Owner premium controls improved.",
      "Locked feature cards improved.",
      "Customer settings panel restrictions improved.",
    ],
  },
  {
    version: "v18.0.0",
    title: "Legendary Dashboard Pro",
    date: "2026-05-18",
    type: "Major Release",
    summary: "Major dashboard release with owner/customer portal, premium controls, and MongoDB-based config.",
    changes: [
      "Added owner dashboard panel.",
      "Added customer dashboard portal.",
      "Added premium/free server logic.",
      "Added locked feature UI.",
      "Added support settings panel.",
      "Added MongoDB-based dashboard config.",
      "Added multiple dashboard modules and server management pages.",
    ],
  },
  {
    version: "v17.0.0",
    title: "Customer Dashboard Foundation",
    date: "2026-05-07",
    type: "Dashboard",
    summary: "Started the customer-facing dashboard portal foundation.",
    changes: [
      "Added customer login flow.",
      "Added customer server selector.",
      "Added customer manage pages.",
      "Added base dashboard routes.",
    ],
  },
  {
    version: "v16.0.0",
    title: "Owner Command Panel Foundation",
    date: "2026-05-07",
    type: "Dashboard",
    summary: "Started the owner admin web panel foundation.",
    changes: [
      "Added Express dashboard server.",
      "Added owner login page.",
      "Added owner server selector.",
      "Added dashboard static assets.",
      "Added basic route protection.",
    ],
  },
  {
    version: "v15.1.0",
    title: "Moderation + Server Tools Expansion",
    date: "2026-03-27",
    type: "Moderation",
    summary: "Expanded moderation, server tools, and command center features.",
    changes: [
      "Added automod command group.",
      "Added anti-link system.",
      "Added anti-spam system.",
      "Added anti-raid planning/features.",
      "Added verify/log/staff channel configuration tools.",
    ],
  },
  {
    version: "v15.0.0",
    title: "Legendary Bot Core Stable",
    date: "2026-03-27",
    type: "Major Release",
    summary: "Stable Discord bot core with slash/prefix command support and persistent config.",
    changes: [
      "Added discord.js v14 base.",
      "Added prefix command handling.",
      "Added slash command registration.",
      "Added MongoDB/JSON persistence improvements.",
      "Added core utility commands.",
    ],
  },
  {
    version: "v14.0.0",
    title: "Giveaway System Concepts",
    date: "2026-03-20",
    type: "Giveaways",
    summary: "Planned and started giveaway-related systems.",
    changes: [
      "Added giveaway command ideas.",
      "Added token concept for repeating giveaways.",
      "Added role bonus entry planning.",
      "Added giveaway log and DM winner concepts.",
    ],
  },
  {
    version: "v13.0.0",
    title: "Sports System Foundation",
    date: "2026-03-15",
    type: "Sports",
    summary: "Started live sports features for cricket and football.",
    changes: [
      "Added sports channel planning.",
      "Added scoreboard update planning.",
      "Added goal alert planning.",
      "Added admin-set channel concept.",
    ],
  },
  {
    version: "v12.0.0",
    title: "Loop Manager + AI Messages",
    date: "2026-03-10",
    type: "AI / Loops",
    summary: "Added automated loop message systems.",
    changes: [
      "Added YAP loop.",
      "Added rumors loop.",
      "Added restore loop after restart.",
      "Added Gemini-based AI text generation.",
    ],
  },
  {
    version: "v11.0.0",
    title: "Roast + Fun AI System",
    date: "2026-03-05",
    type: "Fun / AI",
    summary: "Added roast/fun commands and AI-generated entertainment features.",
    changes: [
      "Added roast command.",
      "Added AI-generated roast style ideas.",
      "Added cooldown/daily-limit planning.",
      "Added fun command category.",
    ],
  },
  {
    version: "v10.0.0",
    title: "Verification + Server Config",
    date: "2026-02-28",
    type: "Server Management",
    summary: "Added verification and server configuration systems.",
    changes: [
      "Added verify channel config.",
      "Added log channel config.",
      "Added staff channel config.",
      "Added per-guild config structure.",
    ],
  },
  {
    version: "v9.0.0",
    title: "Slash Command Support",
    date: "2026-02-20",
    type: "Commands",
    summary: "Added slash command support alongside prefix commands.",
    changes: [
      "Registered slash commands with Discord API.",
      "Kept prefix command compatibility.",
      "Added aliases and command mapping.",
    ],
  },
  {
    version: "v8.0.0",
    title: "Railway Hosting Support",
    date: "2026-02-15",
    type: "Hosting",
    summary: "Moved toward Railway-ready deployment.",
    changes: [
      "Added start script.",
      "Added environment-variable config flow.",
      "Added simple web server for keepalive/dashboard foundation.",
      "Improved Railway deployment compatibility.",
    ],
  },
  {
    version: "v7.0.0",
    title: "MongoDB Persistence",
    date: "2026-02-10",
    type: "Database",
    summary: "Added MongoDB persistence for server settings and future dashboard data.",
    changes: [
      "Added MongoDB connection.",
      "Started moving config away from local JSON only.",
      "Improved restart-safe storage.",
    ],
  },
  {
    version: "v6.0.0",
    title: "Command Categories",
    date: "2026-02-01",
    type: "Commands",
    summary: "Organized commands into categories for easier help and expansion.",
    changes: [
      "Added fun command category.",
      "Added utility command category.",
      "Added moderation command category.",
      "Added system command category.",
    ],
  },
  {
    version: "v5.0.0",
    title: "Basic Moderation Commands",
    date: "2026-01-25",
    type: "Moderation",
    summary: "Added basic moderation command planning/features.",
    changes: [
      "Added warning/mute/kick/ban concepts.",
      "Added moderation log concept.",
      "Added admin-only command checks.",
    ],
  },
  {
    version: "v4.0.0",
    title: "Server Welcome/Goodbye Tools",
    date: "2026-01-15",
    type: "Server Management",
    summary: "Added foundation for welcome/goodbye server messages.",
    changes: [
      "Added welcome message ideas.",
      "Added goodbye message ideas.",
      "Added server branding support concepts.",
    ],
  },
  {
    version: "v3.0.0",
    title: "Bot Utility Commands",
    date: "2026-01-10",
    type: "Utility",
    summary: "Added early utility commands and command handler improvements.",
    changes: [
      "Added ping/status-style commands.",
      "Added command handler cleanup.",
      "Improved error handling for commands.",
    ],
  },
  {
    version: "v2.0.0",
    title: "Prefix Command System",
    date: "2026-01-05",
    type: "Commands",
    summary: "Added the first prefix command foundation.",
    changes: [
      "Added prefix command router.",
      "Added basic command files.",
      "Started using $ as main prefix.",
    ],
  },
  {
    version: "v1.0.0",
    title: "Legendary Bot First Stable Build",
    date: "2026-01-01",
    type: "Core",
    summary: "First stable Legendary Bot structure.",
    changes: [
      "Added Discord client login.",
      "Added basic bot ready event.",
      "Added first command structure.",
      "Added project package setup.",
    ],
  },
  {
    version: "v0.1",
    title: "Project Start",
    date: "2025-12-01",
    type: "Prototype",
    summary: "First idea/prototype stage for Legendary Bot.",
    changes: [
      "Started Legendary Bot concept.",
      "Planned server management tools.",
      "Planned fun commands and moderation support.",
      "Planned future dashboard direction.",
    ],
  },
];

function getChangelogEntries() {
  return CHANGELOG;
}

function getLatestChangelog() {
  return CHANGELOG[0];
}

module.exports = {
  CHANGELOG,
  getChangelogEntries,
  getLatestChangelog,
};
